version: "3.8"

volumes:
  postgres:
    driver: local

services:
  server:
    image: cosmtrek/air:v1.49.0
    container_name: server
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: docker.io/bitnami/postgresql:16.0.0
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=crud
      - POSTGRESQL_LOG_TIMEZONE=GMT
      - POSTGRESQL_TIMEZONE=GMT
