version: "3.8"

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: docker.io/bitnami/postgresql:16.0.0
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=crud
      - POSTGRESQL_LOG_TIMEZONE=GMT
      - POSTGRESQL_TIMEZONE=GMT
